spring:
  application:
    name: notification-service

server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    root: INFO
    com.github.ywoosang.notification: INFO
    software.amazon.awssdk: WARN

# AWS 설정
aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  sqs:
    notification:
      queue:
        url: ${AWS_SQS_NOTIFICATION_QUEUE_URL:}

