spring:
  application:
    name: order-service

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.github.ywoosang.order: INFO
    software.amazon.awssdk: WARN

# AWS 설정
aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  sns:
    topic:
      arn: ${AWS_SNS_TOPIC_ARN:}

